package net.planeteronde.bernard.ui.view.signaletique;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.annotations.DesignRoot;
import com.vaadin.annotations.PropertyId;
import com.vaadin.ui.Button;
import com.vaadin.ui.ComboBox;
import com.vaadin.ui.DateField;
import com.vaadin.ui.GridLayout;
import com.vaadin.ui.TextField;
import com.vaadin.ui.declarative.Design;

/** 
 * !! DO NOT EDIT THIS FILE !!
 * 
 * This class is generated by Vaadin Designer and will be overwritten.
 * 
 * Please make a subclass with logic and additional interfaces as needed,
 * e.g class LoginView extends LoginDesign implements View { }
 */
@DesignRoot
@AutoGenerated
@SuppressWarnings("serial")
public class SignaletiqueViewDesign extends GridLayout {
	protected TextField nom;
	protected Button annuler;
	@PropertyId("filiale")
	protected ComboBox<net.planeteronde.bernard.backend.data.entity.Projet.Filiale> filiale;
	protected TextField source;
	protected ComboBox<net.planeteronde.bernard.backend.data.entity.Projet.Client> client;
	protected TextField architecte;
	protected ComboBox<net.planeteronde.bernard.backend.data.entity.Projet.Metier> metier;
	protected ComboBox<net.planeteronde.bernard.backend.data.entity.Projet.LoB> lob;
	protected ComboBox<net.planeteronde.bernard.backend.data.entity.Projet.SubLoB> subLob;
	protected ComboBox<net.planeteronde.bernard.backend.data.entity.Projet.TypeOuvrage> typeOuvrage;
	protected TextField montant_marche;
	protected TextField delai_client;
	protected DateField date_signature;
	protected TextField delai_technique_prevu;
	protected DateField date_ouverture;
	protected DateField date_fin;
	protected TextField nom_dir_BU;
	protected TextField prenom_dir_BU;
	protected TextField email_dir_BU;
	protected TextField nom_chage_aff;
	protected TextField prenom_charge_aff;
	protected TextField email_charge_aff;
	protected TextField nom_resp_conc;
	protected TextField prenom_resp_conc;
	protected TextField email_resp_conc;
	protected TextField nom_resp_sav;
	protected TextField prenom_resp_sav;
	protected TextField email_resp_sav;
	protected Button enregistrer;
	protected Button supprimer;

	public SignaletiqueViewDesign() {
		Design.read(this);
	}
}
